import type { CaseFormData } from './case-schema';

export interface CaseTemplate {
  id: string;
  name: string;
  specialty: CaseFormData['specialty'];
  difficulty: CaseFormData['difficulty'];
  content: Partial<CaseFormData>;
}

export const caseTemplates: CaseTemplate[] = [
  {
    id: 'ami',
    name: 'Acute Myocardial Infarction',
    specialty: 'cardiology',
    difficulty: 'intermediate',
    content: {
      title: 'Acute Myocardial Infarction Case',
      specialty: 'cardiology',
      difficulty: 'intermediate',
      tags: ['cardiology', 'AMI', 'chest pain'],
      patient_details: {
        age: 55,
        gender: 'male',
        occupation: 'office worker',
      },
      chief_complaint_history: {
        chief_complaint: 'Crushing substernal chest pain radiating to left arm and jaw, associated with diaphoresis and dyspnea.',
        hpi_duration: '45 minutes',
        hpi_onset: 'sudden while watching TV',
        hpi_aggravating: 'exertion',
        hpi_relieving: 'rest (partial)',
        hpi_additional: '8/10 pain severity',
        associated_symptoms: 'nausea, diaphoresis, lightheadedness',
      },
      medical_history: {
        past_medical_history: ['hypertension', 'hyperlipidemia'],
        custom_medical_history: 'No prior surgeries or hospitalizations',
        family_history: 'Father had MI at 60, mother has type 2 diabetes',
        social_history_smoking: 'Former smoker, quit 10 years ago, 1 pack per day for 20 years',
        social_history_alcohol: '1-2 drinks per week',
        social_history_occupation: 'Sedentary office job',
        allergies: ['Penicillin (rash)'],
      },
      current_medications: [
        { name: 'Lisinopril', dose: '10 mg', frequency: 'once daily' },
        { name: 'Atorvastatin', dose: '20 mg', frequency: 'once daily' },
      ],
      review_of_systems: {
        cardiovascular: 'Positive for chest pain, palpitations',
        respiratory: 'Positive for dyspnea, no wheezing',
        gastrointestinal: 'Positive for nausea, no vomiting',
        neurological: 'Positive for lightheadedness, no focal deficits',
        other: 'Positive for diaphoresis',
      },
      examination_findings: {
        general_appearance: 'Anxious and diaphoretic, appears uncomfortable',
        vital_signs: {
          bp_systolic: 145,
          bp_diastolic: 92,
          hr: 110,
          rr: 22,
          temp: 98.8,
          spo2: 95,
        },
        systemic: {
          cardiovascular: 'Tachycardic, regular rhythm, no murmurs, rubs or gallops; JVP 8 cm H2O',
          respiratory: 'Clear to auscultation bilaterally, no rales or wheezes',
          gastrointestinal: 'Soft, non-tender, non-distended abdomen, bowel sounds present',
          neurological: 'Alert and oriented x 3, no focal weakness or sensory changes',
        },
      },
      investigations: [
        {
          type: 'imaging',
          test_name: '12-lead ECG',
          result: 'ST-segment elevation in leads II, III, aVF, with reciprocal changes in I and aVL',
          date: new Date().toISOString(),
          interpretation: 'Inferior STEMI',
        },
        {
          type: 'lab',
          test_name: 'Troponin I',
          result: '2.5 ng/mL',
          normal_range: '< 0.04 ng/mL',
          date: new Date().toISOString(),
          interpretation: 'Elevated, consistent with myocardial injury',
        },
      ],
      diagnosis_management: {
        provisional_diagnosis: 'Inferior ST-elevation myocardial infarction (STEMI)',
        differential_diagnoses: ['Pericarditis', 'Pulmonary embolism', 'Gastroesophageal reflux disease', 'Costochondritis'],
        final_diagnosis: 'Inferior STEMI due to right coronary artery occlusion (confirmed on coronary angiography)',
        treatment_plan: 'Primary PCI with drug-eluting stent to RCA, aspirin 325 mg loading dose, clopidogrel 600 mg loading dose, heparin infusion, high-intensity statin, beta-blocker, ACE inhibitor, and dual antiplatelet therapy for 12 months',
        medications_prescribed: [
          { drug: 'Aspirin', dose: '81 mg', frequency: 'once daily', duration: 'Indefinite' },
          { drug: 'Clopidogrel', dose: '75 mg', frequency: 'once daily', duration: '12 months' },
          { drug: 'Atorvastatin', dose: '80 mg', frequency: 'once daily', duration: 'Indefinite' },
          { drug: 'Metoprolol succinate', dose: '25 mg', frequency: 'once daily', duration: 'Indefinite' },
          { drug: 'Lisinopril', dose: '10 mg', frequency: 'once daily', duration: 'Indefinite' },
        ],
        follow_up_plan: 'Follow up with cardiology in 1 week, then monthly for 3 months, cardiac rehabilitation program, repeat echocardiogram in 6-8 weeks',
        prognosis: 'Good prognosis with early successful reperfusion; decreased LV function possible depending on infarct size',
      },
      learning_points: [
        'Early recognition of STEMI is crucial for timely reperfusion therapy',
        '12-lead ECG remains the initial diagnostic test of choice for suspected ACS',
        'Time is muscle - door-to-balloon time should be <90 minutes',
        'Dual antiplatelet therapy is essential post-PCI',
        'Risk factor modification (smoking, hypertension, hyperlipidemia, diabetes) is key to secondary prevention',
      ],
    },
  },
  {
    id: 'diabetes',
    name: 'Type 2 Diabetes Mellitus',
    specialty: 'internal_medicine',
    difficulty: 'beginner',
    content: {
      title: 'Type 2 Diabetes Mellitus Case',
      specialty: 'internal_medicine',
      difficulty: 'beginner',
      tags: ['diabetes', 'endocrinology'],
      patient_details: {
        age: 45,
        gender: 'female',
        occupation: 'teacher',
      },
      chief_complaint_history: {
        chief_complaint: 'Polyuria, polydipsia, and unintended weight loss over 2 months',
        hpi_duration: '2 months',
        hpi_onset: 'gradual',
        hpi_additional: '15 lb weight loss despite normal appetite',
        associated_symptoms: 'fatigue, blurred vision',
      },
      medical_history: {
        past_medical_history: ['obesity'],
        family_history: 'Mother and maternal aunt have type 2 diabetes',
        social_history_smoking: 'Never smoked',
        social_history_alcohol: 'Occasional wine with meals',
        social_history_occupation: 'Elementary school teacher',
        allergies: ['Sulfa (hives)'],
      },
      current_medications: [
        { name: 'Multivitamin', dose: '1 tablet', frequency: 'once daily' },
      ],
      review_of_systems: {
        neurological: 'Positive for blurred vision, no numbness or tingling',
        other: 'Positive for fatigue, weight loss, polyuria, and polydipsia',
      },
      examination_findings: {
        general_appearance: 'Alert and oriented, appears slightly fatigued',
        vital_signs: {
          bp_systolic: 132,
          bp_diastolic: 84,
          hr: 78,
          rr: 16,
          temp: 98.6,
          spo2: 99,
        },
        systemic: {
          cardiovascular: 'Regular rate and rhythm, no murmurs',
          respiratory: 'Clear bilaterally',
          gastrointestinal: 'Soft, non-tender, non-distended',
          neurological: 'No sensory deficits, reflexes intact',
        },
      },
      investigations: [
        {
          type: 'lab',
          test_name: 'Fasting Plasma Glucose',
          result: '180 mg/dL',
          normal_range: '< 100 mg/dL',
          date: new Date().toISOString(),
          interpretation: 'Consistent with diabetes',
        },
        {
          type: 'lab',
          test_name: 'HbA1c',
          result: '7.8%',
          normal_range: '4.0-5.6%',
          date: new Date().toISOString(),
          interpretation: 'Elevated, average glucose over past 3 months ~170 mg/dL',
        },
      ],
      diagnosis_management: {
        provisional_diagnosis: 'Type 2 diabetes mellitus',
        differential_diagnoses: ['Type 1 diabetes', 'Gestational diabetes (if pregnant)', 'Cushing syndrome', 'Pancreatic insufficiency'],
        final_diagnosis: 'Type 2 diabetes mellitus, newly diagnosed',
        treatment_plan: 'Metformin 500 mg twice daily, dietary counseling (carb counting, portion control), regular exercise (150 minutes per week of moderate activity), blood glucose monitoring at home',
        medications_prescribed: [
          { drug: 'Metformin ER', dose: '500 mg', frequency: 'twice daily', duration: 'Indefinite' },
        ],
        follow_up_plan: 'Follow up in 3 months for HbA1c check, then quarterly as needed; referral to dietitian, eye exam referral, foot exam',
        prognosis: 'Excellent prognosis with good glycemic control; risk of complications reduced with tight control',
      },
      learning_points: [
        'Classic symptoms of diabetes include polyuria, polydipsia, polyphagia, and weight loss',
        'Fasting glucose ≥ 126 mg/dL or HbA1c ≥ 6.5% is diagnostic for diabetes',
        'Lifestyle modifications (diet and exercise) are first-line for type 2 diabetes',
        'Metformin is the initial pharmacologic agent of choice',
        'Regular monitoring (HbA1c, eye exams, foot exams) is important for complication prevention',
      ],
    },
  },
  {
    id: 'cap',
    name: 'Community-Acquired Pneumonia',
    specialty: 'pulmonology',
    difficulty: 'intermediate',
    content: {
      title: 'Community-Acquired Pneumonia Case',
      specialty: 'pulmonology',
      difficulty: 'intermediate',
      tags: ['pneumonia', 'pulmonology', 'infection'],
      patient_details: {
        age: 68,
        gender: 'male',
        occupation: 'retired teacher',
      },
      chief_complaint_history: {
        chief_complaint: 'Cough with yellow sputum, fever, and right-sided chest pain for 4 days',
        hpi_duration: '4 days',
        hpi_onset: 'gradual',
        hpi_aggravating: 'Deep breathing, coughing',
        hpi_relieving: 'Rest, acetaminophen',
        hpi_additional: 'Productive cough with thick yellow sputum, subjective fever up to 102°F at home',
        associated_symptoms: 'Dyspnea, fatigue, loss of appetite',
      },
      medical_history: {
        past_medical_history: ['hypertension', 'COPD'],
        family_history: 'Father had lung cancer, mother had COPD',
        social_history_smoking: 'Former smoker, quit 5 years ago, 2 packs per day for 35 years',
        social_history_alcohol: 'Occasional beer on weekends',
        social_history_occupation: 'Retired high school teacher',
        allergies: ['Erythromycin (nausea)'],
      },
      current_medications: [
        { name: 'Lisinopril', dose: '20 mg', frequency: 'once daily' },
        { name: 'Tiotropium', dose: '18 mcg', frequency: 'once daily' },
        { name: 'Albuterol', dose: '2 puffs', frequency: 'every 4-6 hours as needed' },
      ],
      review_of_systems: {
        respiratory: 'Positive for cough, dyspnea, pleuritic chest pain',
        gastrointestinal: 'Positive for decreased appetite, no nausea/vomiting',
        constitutional: 'Positive for fever, fatigue, chills',
      },
      examination_findings: {
        general_appearance: 'Mild respiratory distress, appears ill',
        vital_signs: {
          bp_systolic: 128,
          bp_diastolic: 76,
          hr: 105,
          rr: 24,
          temp: 101.8,
          spo2: 92,
        },
        systemic: {
          cardiovascular: 'Tachycardic, regular rhythm, no murmurs',
          respiratory: 'Tachypneic, right lower lobe crackles, decreased breath sounds in right base, increased tactile fremitus',
          gastrointestinal: 'Soft, non-tender, non-distended abdomen',
        },
      },
      investigations: [
        {
          type: 'imaging',
          test_name: 'Chest X-ray PA and lateral',
          result: 'Right lower lobe consolidation',
          date: new Date().toISOString(),
          interpretation: 'Consistent with community-acquired pneumonia',
        },
        {
          type: 'lab',
          test_name: 'CBC with differential',
          result: 'WBC 18,500/mm³ with 85% neutrophils',
          normal_range: 'WBC 4,500-11,000/mm³, neutrophils 40-75%',
          date: new Date().toISOString(),
          interpretation: 'Leukocytosis with left shift, consistent with bacterial infection',
        },
        {
          type: 'lab',
          test_name: 'Pulse oximetry',
          result: '92% on room air',
          normal_range: '95-100%',
          date: new Date().toISOString(),
          interpretation: 'Mild hypoxemia',
        },
      ],
      diagnosis_management: {
        provisional_diagnosis: 'Community-acquired pneumonia, right lower lobe',
        differential_diagnoses: ['Acute bronchitis', 'Pulmonary embolism', 'Aspiration pneumonia', 'Lung cancer with post-obstructive pneumonia'],
        final_diagnosis: 'Community-acquired pneumonia, right lower lobe, typical bacterial etiology',
        treatment_plan: 'Hospital admission, supplemental oxygen to keep SpO2 >94%, ceftriaxone 1 g IV daily plus azithromycin 500 mg IV daily, acetaminophen for fever/pain, albuterol as needed, hydration',
        medications_prescribed: [
          { drug: 'Ceftriaxone', dose: '1 g', frequency: 'IV daily', duration: '7 days' },
          { drug: 'Azithromycin', dose: '500 mg', frequency: 'IV daily', duration: '5 days' },
          { drug: 'Acetaminophen', dose: '650 mg', frequency: 'every 6 hours as needed', duration: '7 days' },
          { drug: 'Albuterol', dose: '2 puffs', frequency: 'every 4 hours as needed', duration: '10 days' },
        ],
        follow_up_plan: 'Follow up with primary care in 1 week, repeat chest x-ray in 6 weeks, continue COPD medications, smoking cessation counseling',
        prognosis: 'Good prognosis with appropriate antibiotic therapy; full recovery expected',
      },
      learning_points: [
        'Classic presentation of bacterial pneumonia includes fever, productive cough, and pleuritic chest pain',
        'CURB-65 score helps guide admission decision',
        'Antibiotic choice should cover typical (S. pneumoniae) and atypical (Mycoplasma, Legionella, Chlamydia) pathogens',
        'Smoking is a major risk factor for pneumonia',
        'Follow-up chest x-ray is important to ensure resolution and rule out underlying pathology',
      ],
    },
  },
  {
    id: 'appendicitis',
    name: 'Acute Appendicitis',
    specialty: 'gastroenterology',
    difficulty: 'intermediate',
    content: {
      title: 'Acute Appendicitis Case',
      specialty: 'gastroenterology',
      difficulty: 'intermediate',
      tags: ['appendicitis', 'surgery', 'abdominal pain'],
      patient_details: {
        age: 22,
        gender: 'male',
        occupation: 'college student',
      },
      chief_complaint_history: {
        chief_complaint: 'Abdominal pain starting around the belly button and moving to the right lower quadrant',
        hpi_duration: '18 hours',
        hpi_onset: 'sudden',
        hpi_aggravating: 'Movement, coughing, deep breathing',
        hpi_relieving: 'Lying still',
        hpi_additional: 'Pain initially periumbilical then localized to RLQ over the last 6 hours',
        associated_symptoms: 'Anorexia, nausea, 2 episodes of vomiting, low-grade fever',
      },
      medical_history: {
        past_medical_history: [],
        family_history: 'Appendectomy in brother at age 18',
        social_history_smoking: 'Never smoked',
        social_history_alcohol: 'Occasional social drinking on weekends',
        social_history_occupation: 'College junior, computer science major',
        allergies: ['No known allergies'],
      },
      current_medications: [],
      review_of_systems: {
        gastrointestinal: 'Positive for anorexia, nausea, vomiting; no diarrhea',
        constitutional: 'Positive for low-grade fever, malaise',
      },
      examination_findings: {
        general_appearance: 'Lies still on stretcher, appears uncomfortable',
        vital_signs: {
          bp_systolic: 130,
          bp_diastolic: 82,
          hr: 95,
          rr: 18,
          temp: 100.4,
          spo2: 99,
        },
        systemic: {
          gastrointestinal: 'Tender to palpation at McBurney\'s point, positive Rovsing\'s sign, positive psoas sign, positive obturator sign, guarding and rebound tenderness present',
        },
      },
      investigations: [
        {
          type: 'lab',
          test_name: 'CBC with differential',
          result: 'WBC 16,200/mm³ with 82% neutrophils',
          normal_range: 'WBC 4,500-11,000/mm³, neutrophils 40-75%',
          date: new Date().toISOString(),
          interpretation: 'Leukocytosis with left shift',
        },
        {
          type: 'imaging',
          test_name: 'Abdominal and pelvic CT scan with contrast',
          result: 'Enlarged appendix (10 mm) with wall enhancement, periappendiceal fat stranding',
          date: new Date().toISOString(),
          interpretation: 'Findings consistent with acute appendicitis',
        },
      ],
      diagnosis_management: {
        provisional_diagnosis: 'Acute appendicitis',
        differential_diagnoses: ['Acute gastroenteritis', 'Mesenteric lymphadenitis', 'Ectopic pregnancy (in females)', 'Ovarian torsion', 'Urinary tract infection', 'Kidney stones'],
        final_diagnosis: 'Acute appendicitis',
        treatment_plan: 'NPO, IV fluids, analgesia, urgent laparoscopic appendectomy, perioperative antibiotics',
        medications_prescribed: [
          { drug: 'Cefoxitin', dose: '2 g', frequency: 'IV preoperatively', duration: 'Single dose' },
          { drug: 'Morphine', dose: '2-4 mg', frequency: 'IV every 2 hours as needed', duration: 'Perioperative' },
        ],
        follow_up_plan: 'Post-op follow-up with surgery in 1 week, return to normal activity in 2-4 weeks',
        prognosis: 'Excellent prognosis with appendectomy, low risk of complications with early intervention',
      },
      learning_points: [
        'Classic appendicitis presentation: periumbilical pain migrating to RLQ, plus anorexia, nausea, vomiting',
        'McBurney\'s point tenderness is the most important physical exam finding',
        'CT scan is the imaging modality of choice for confirming appendicitis',
        'Appendectomy is the definitive treatment, usually performed laparoscopically',
        'Delay in treatment increases risk of perforation',
      ],
    },
  },
  {
    id: 'stroke',
    name: 'Ischemic Stroke',
    specialty: 'neurology',
    difficulty: 'advanced',
    content: {
      title: 'Acute Ischemic Stroke Case',
      specialty: 'neurology',
      difficulty: 'advanced',
      tags: ['stroke', 'neurology', 'cerebrovascular'],
      patient_details: {
        age: 72,
        gender: 'female',
        occupation: 'retired nurse',
      },
      chief_complaint_history: {
        chief_complaint: 'Sudden onset left-sided weakness and slurred speech',
        hpi_duration: '90 minutes',
        hpi_onset: 'sudden while eating breakfast',
        hpi_additional: 'Family noticed patient dropped fork, couldn\'t speak clearly, left arm and leg weak',
        associated_symptoms: 'Left facial droop, left-sided numbness',
      },
      medical_history: {
        past_medical_history: ['hypertension', 'atrial fibrillation', 'hyperlipidemia', 'type 2 diabetes'],
        family_history: 'Father had stroke at 75, mother had MI at 70',
        social_history_smoking: 'Never smoked',
        social_history_alcohol: '1 glass of wine daily',
        social_history_occupation: 'Retired registered nurse',
        allergies: ['No known allergies'],
      },
      current_medications: [
        { name: 'Metoprolol succinate', dose: '50 mg', frequency: 'once daily' },
        { name: 'Atorvastatin', dose: '40 mg', frequency: 'once daily' },
        { name: 'Metformin', dose: '1000 mg', frequency: 'twice daily' },
        { name: 'Apixaban', dose: '5 mg', frequency: 'twice daily' },
      ],
      review_of_systems: {
        neurological: 'Positive for left-sided weakness, facial droop, slurred speech, numbness; no headache or loss of consciousness',
        cardiovascular: 'No chest pain, no palpitations',
      },
      examination_findings: {
        general_appearance: 'Alert and oriented x 3, appears anxious',
        vital_signs: {
          bp_systolic: 175,
          bp_diastolic: 95,
          hr: 92,
          rr: 18,
          temp: 98.6,
          spo2: 98,
        },
        systemic: {
          cardiovascular: 'Irregularly irregular rhythm, no murmurs',
          neurological: 'Left facial droop, left arm drift, left leg drift, left-sided sensory deficit to light touch, slurred speech (dysarthria), NIHSS score 6',
        },
      },
      investigations: [
        {
          type: 'imaging',
          test_name: 'Non-contrast head CT',
          result: 'No hemorrhage, no early infarct signs',
          date: new Date().toISOString(),
          interpretation: 'Negative for hemorrhage, consistent with acute ischemic stroke',
        },
        {
          type: 'lab',
          test_name: 'CBC, BMP, coagulation profile',
          result: 'WBC 9,200/mm³, glucose 160 mg/dL, INR 2.1 (on apixaban)',
          normal_range: 'WBC 4,500-11,000/mm³, glucose 70-100 mg/dL, INR 0.8-1.2',
          date: new Date().toISOString(),
          interpretation: 'Mild hyperglycemia, therapeutic INR',
        },
      ],
      diagnosis_management: {
        provisional_diagnosis: 'Acute ischemic stroke, right hemisphere',
        differential_diagnoses: ['Intracerebral hemorrhage', 'Seizure with Todd\'s paralysis', 'Hypoglycemia', 'Migraine with aura', 'Complex partial seizure'],
        final_diagnosis: 'Acute ischemic stroke involving right middle cerebral artery territory, likely cardioembolic due to atrial fibrillation',
        treatment_plan: 'Patient outside tPA window, admit to stroke unit, maintain BP <180/105, continue apixaban, swallow evaluation, physical/occupational therapy, speech therapy, stroke education',
        medications_prescribed: [
          { drug: 'Atorvastatin', dose: '80 mg', frequency: 'once daily', duration: 'Indefinite' },
          { drug: 'Metoprolol succinate', dose: '50 mg', frequency: 'once daily', duration: 'Indefinite' },
          { drug: 'Metformin', dose: '1000 mg', frequency: 'twice daily', duration: 'Indefinite' },
          { drug: 'Apixaban', dose: '5 mg', frequency: 'twice daily', duration: 'Indefinite' },
        ],
        follow_up_plan: 'Follow up with neurology in 2 weeks, physical/OT/speech therapy as an outpatient, MRI brain in 1 week, cardiac evaluation including echocardiogram, smoking cessation (if applicable)',
        prognosis: 'Moderate prognosis; potential for significant recovery with rehabilitation; risk of recurrent stroke is high in first year',
      },
      learning_points: [
        'Act FAST: Face drooping, Arm weakness, Speech difficulty, Time to call 911',
        'Time is brain - tPA window is 4.5 hours from symptom onset in eligible patients',
        'Atrial fibrillation is a major risk factor for cardioembolic stroke',
        'Non-contrast head CT first to rule out hemorrhage',
        'Secondary prevention includes antiplatelets/anticoagulants, statins, BP control',
      ],
    },
  },
  {
    id: 'thyroid',
    name: 'Hypothyroidism',
    specialty: 'internal_medicine',
    difficulty: 'beginner',
    content: {
      title: 'Primary Hypothyroidism Case',
      specialty: 'internal_medicine',
      difficulty: 'beginner',
      tags: ['hypothyroidism', 'endocrinology', 'thyroid'],
      patient_details: {
        age: 52,
        gender: 'female',
        occupation: 'librarian',
      },
      chief_complaint_history: {
        chief_complaint: 'Fatigue, weight gain, and cold intolerance for 3 months',
        hpi_duration: '3 months',
        hpi_onset: 'gradual',
        hpi_additional: 'Gained 15 lbs despite no change in diet, feeling cold when others are comfortable',
        associated_symptoms: 'Constipation, dry skin, hair loss, muscle cramps, depressed mood',
      },
      medical_history: {
        past_medical_history: ['vitamin D deficiency'],
        family_history: 'Mother has hypothyroidism, sister has Hashimoto\'s',
        social_history_smoking: 'Never smoked',
        social_history_alcohol: 'Rare, less than 1 drink per month',
        social_history_occupation: 'Librarian, mostly sedentary job',
        allergies: ['No known allergies'],
      },
      current_medications: [
        { name: 'Vitamin D3', dose: '1000 IU', frequency: 'once daily' },
      ],
      review_of_systems: {
        dermatological: 'Positive for dry skin, brittle nails, hair loss',
        gastrointestinal: 'Positive for constipation',
        musculoskeletal: 'Positive for muscle cramps, myalgias',
        psychiatric: 'Positive for mild depression, difficulty concentrating',
        constitutional: 'Positive for fatigue, weight gain, cold intolerance',
      },
      examination_findings: {
        general_appearance: 'Tired appearance, slow movements and speech',
        vital_signs: {
          bp_systolic: 120,
          bp_diastolic: 78,
          hr: 58,
          rr: 16,
          temp: 97.2,
          spo2: 99,
        },
        systemic: {
          cardiovascular: 'Bradycardic, regular rhythm',
          gastrointestinal: 'Mild abdominal distension, decreased bowel sounds',
          dermatological: 'Dry, cool skin, brittle nails, thin hair',
          thyroid: 'Diffusely enlarged, non-tender thyroid (goiter)',
        },
      },
      investigations: [
        {
          type: 'lab',
          test_name: 'TSH',
          result: '18.5 mIU/L',
          normal_range: '0.5-4.5 mIU/L',
          date: new Date().toISOString(),
          interpretation: 'Elevated, consistent with primary hypothyroidism',
        },
        {
          type: 'lab',
          test_name: 'Free T4',
          result: '0.6 ng/dL',
          normal_range: '0.8-1.8 ng/dL',
          date: new Date().toISOString(),
          interpretation: 'Low, confirms hypothyroidism',
        },
        {
          type: 'lab',
          test_name: 'TPO antibodies',
          result: 'Positive, high titer',
          normal_range: 'Negative',
          date: new Date().toISOString(),
          interpretation: 'Consistent with Hashimoto\'s thyroiditis',
        },
      ],
      diagnosis_management: {
        provisional_diagnosis: 'Primary hypothyroidism',
        differential_diagnoses: ['Subclinical hypothyroidism', 'Secondary hypothyroidism (pituitary cause)', 'Euthyroid sick syndrome', 'Depression', 'Chronic fatigue syndrome'],
        final_diagnosis: 'Primary hypothyroidism due to Hashimoto\'s thyroiditis',
        treatment_plan: 'Levothyroxine replacement therapy, starting at 50 mcg daily, recheck TSH in 6-8 weeks',
        medications_prescribed: [
          { drug: 'Levothyroxine', dose: '50 mcg', frequency: 'once daily (empty stomach, 30-60 minutes before food)', duration: 'Indefinite' },
        ],
        follow_up_plan: 'Follow up in 8 weeks for repeat TSH, adjust dose as needed; once stabilized, annual TSH monitoring; continue vitamin D supplementation',
        prognosis: 'Excellent prognosis with appropriate thyroid hormone replacement; full symptom resolution expected',
      },
      learning_points: [
        'Common symptoms of hypothyroidism include fatigue, cold intolerance, weight gain, dry skin, and constipation',
        'TSH is the initial screening test; elevated TSH + low free T4 confirms primary hypothyroidism',
        'Hashimoto\'s thyroiditis is the most common cause of hypothyroidism in iodine-sufficient areas',
        'Levothyroxine is the treatment of choice, taken on an empty stomach',
        'Pregnant women have higher thyroid hormone requirements',
      ],
    },
  },
];
