import type { CaseFormData } from './case-schema';

export interface CaseTemplate {
  id: string;
  name: string;
  specialty: CaseFormData['specialty'];
  difficulty: CaseFormData['difficulty'];
  content: Partial<CaseFormData>;
}

export const caseTemplates: CaseTemplate[] = [
  {
    id: 'ami',
    name: 'Acute Myocardial Infarction',
    specialty: 'cardiology',
    difficulty: 'intermediate',
    content: {
      title: 'Acute Myocardial Infarction Case',
      specialty: 'cardiology',
      difficulty: 'intermediate',
      tags: ['cardiology', 'AMI', 'chest pain'],
      patient_details: {
        case_no: 'AMI-2026-001',
        patient_name: 'John Doe',
        age: 55,
        sex: 'male',
        religion: 'Christian',
        occupation: 'Office worker',
        address: '123 Medical Park Drive, City',
        date_of_admission: '2026-08-20',
      },
      history: {
        presenting_complaints: 'Crushing substernal chest pain radiating to left arm and jaw for 45 minutes.',
        history_of_present_illness: 'Onset was sudden while watching TV. Severity 8/10, associated with diaphoresis, dyspnea, and nausea. Aggravated by exertion, partially relieved by rest.',
        past_history: 'Hypertension, hyperlipidemia. No prior surgeries.',
        personal_history: 'Former smoker (20 pack-years, quit 10 years ago). Moderate alcohol consumption.',
        treatment_history: 'Lisinopril 10mg OD, Atorvastatin 20mg OD.',
        family_history: 'Father had MI at age 60.',
        menstrual_history: 'N/A',
        obstetric_history: 'N/A',
        socio_economic_history: 'Middle income, lives with family.',
        any_other: 'No known drug allergies besides Penicillin (rash).',
      },
      general_physical_examination: {
        consciousness_orientation: 'Alert, conscious, oriented x 3, in moderate painful distress.',
        pallor: 'Mild pallor present',
        cyanosis: 'Absent',
        icterus: 'Absent',
        peripheral_oedema: 'Absent',
        clubbing: 'Absent',
        jvp: 'Elevated (8 cm H2O)',
        lymph_nodes: { cervical: 'Not palpable', axillary: 'Not palpable', inguinal: 'Not palpable' },
        pulse: '110 bpm, regular, good volume',
        bp: '145/92 mmHg',
        respiratory_rate: '22 breaths/min',
        temperature: '98.8 °F',
        other_significant_findings: 'Diaphoretic, cold peripheries.',
      },
      systemic_examination: {
        cardiovascular_system: 'Tachycardic, S1 S2 present, no murmurs or rubs.',
        respiratory_system: 'Clear to auscultation bilaterally, no rales or wheezes.',
        nervous_system: 'Grossly intact, no focal neurological deficits.',
        genito_urinary_system: 'Normal external genitalia, intact output.',
        gastrointestinal_system: 'Soft, non-tender, non-distended.',
      },
      local_examination: {
        region: 'Precordium',
        inspection: 'No visible scars, pulsation at apex impulse.',
        palpation: 'Apex beat in 5th ICS MCL, non-heaving.',
        percussion: 'Normal cardiac dullness.',
        auscultation: 'S1 S2 heard, no pericardial friction rub.',
      },
      diagnosis: {
        provisional_diagnosis: 'Inferior ST-elevation myocardial infarction (STEMI)',
        differential_diagnosis: 'Pericarditis, Pulmonary Embolism, Aortic Dissection, GERD',
      },
      investigations_info: {
        investigations_confirmation: '12-lead ECG shows ST-segment elevation in leads II, III, aVF with reciprocal ST depression in I and aVL. Troponin I elevated at 2.5 ng/mL.',
        investigations_staging: 'Echocardiogram shows inferior wall hypokinesis with LVEF 50%. Coronary Angiogram shows total occlusion of RCA.',
      },
      custom_fields: [],
    },
  },
  {
    id: 'diabetes',
    name: 'Type 2 Diabetes Mellitus',
    specialty: 'internal_medicine',
    difficulty: 'beginner',
    content: {
      title: 'Type 2 Diabetes Mellitus Case',
      specialty: 'internal_medicine',
      difficulty: 'beginner',
      tags: ['diabetes', 'endocrinology'],
      patient_details: {
        case_no: 'DM2-2026-002',
        patient_name: 'Jane Smith',
        age: 45,
        sex: 'female',
        religion: 'Hindu',
        occupation: 'Teacher',
        address: '456 Central Ave, Metro City',
        date_of_admission: '2026-08-22',
      },
      history: {
        presenting_complaints: 'Polyuria, polydipsia, and unintended weight loss for 2 months.',
        history_of_present_illness: '15 lb weight loss over 2 months despite increased appetite. Complains of fatigue and blurred vision.',
        past_history: 'Obesity. No chronic hospitalizations.',
        personal_history: 'Non-smoker, occasional social wine.',
        treatment_history: 'Multivitamins.',
        family_history: 'Mother and maternal aunt have Type 2 Diabetes.',
        menstrual_history: 'Regular cycles, 28 days.',
        obstetric_history: 'P2L2, normal vaginal deliveries.',
        socio_economic_history: 'Upper middle class.',
        any_other: 'Sulfa allergy (hives).',
      },
      general_physical_examination: {
        consciousness_orientation: 'Conscious, alert, oriented.',
        pallor: 'Absent',
        cyanosis: 'Absent',
        icterus: 'Absent',
        peripheral_oedema: 'Absent',
        clubbing: 'Absent',
        jvp: 'Normal',
        lymph_nodes: { cervical: 'Not palpable', axillary: 'Not palpable', inguinal: 'Not palpable' },
        pulse: '78 bpm, regular',
        bp: '132/84 mmHg',
        respiratory_rate: '16 breaths/min',
        temperature: '98.6 °F',
        other_significant_findings: 'BMI 31.2 kg/m²',
      },
      systemic_examination: {
        respiratory_system: 'Bilateral clear breath sounds.',
        cardiovascular_system: 'Regular rhythm, S1 S2 normal.',
        nervous_system: 'Sensory intact in lower limbs, monofilament testing normal.',
        genito_urinary_system: 'Normal.',
        gastrointestinal_system: 'Soft, non-tender.',
      },
      local_examination: {
        region: 'Abdomen',
        inspection: 'Central obesity, no striations.',
        palpation: 'Soft, non-tender.',
        percussion: 'Tympanic.',
        auscultation: 'Bowel sounds present.',
      },
      diagnosis: {
        provisional_diagnosis: 'Type 2 Diabetes Mellitus, newly diagnosed',
        differential_diagnosis: 'Type 1 Diabetes Mellitus, Cushing Syndrome',
      },
      investigations_info: {
        investigations_confirmation: 'Fasting Plasma Glucose 180 mg/dL, HbA1c 7.8%.',
        investigations_staging: 'Urine microalbumin/creatinine ratio normal (15 mg/g). Lipid panel shows Mild Hyperlipidemia.',
      },
      custom_fields: [],
    },
  },
];
